
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Image image4;

	private global::Gtk.VSeparator vseparator1;

	private global::Gtk.Image image5;

	private global::Gtk.HSeparator hseparator1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox3;

	private global::Gtk.Label label1;

	private global::Gtk.HScrollbar hscrollbar1;

	private global::Gtk.SpinButton spinbutton1;

	private global::Gtk.HBox hbox4;

	private global::Gtk.Label label2;

	private global::Gtk.HScrollbar hscrollbar2;

	private global::Gtk.SpinButton spinbutton2;

	private global::Gtk.Label GtkLabel1;

	private global::Gtk.HBox hbox6;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Button button1;

	private global::Gtk.Button button3;

	private global::Gtk.Fixed fixed1;

	private global::Gtk.CheckButton checkbutton1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image();
		this.image4.Name = "image4";
		this.hbox1.Add(this.image4);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image4]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vseparator1 = new global::Gtk.VSeparator();
		this.vseparator1.Name = "vseparator1";
		this.hbox1.Add(this.vseparator1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vseparator1]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.image5 = new global::Gtk.Image();
		this.image5.Name = "image5";
		this.hbox1.Add(this.image5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.image5]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add(this.hseparator1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hseparator1]));
		w5.Position = 1;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vbox2.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator3]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Minimum");
		this.hbox3.Add(this.label1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label1]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.hscrollbar1 = new global::Gtk.HScrollbar(null);
		this.hscrollbar1.Name = "hscrollbar1";
		this.hscrollbar1.Adjustment.Upper = 100D;
		this.hscrollbar1.Adjustment.PageIncrement = 10D;
		this.hscrollbar1.Adjustment.PageSize = 10D;
		this.hscrollbar1.Adjustment.StepIncrement = 1D;
		this.hbox3.Add(this.hscrollbar1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.hscrollbar1]));
		w8.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.spinbutton1 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbutton1.CanFocus = true;
		this.spinbutton1.Name = "spinbutton1";
		this.hbox3.Add(this.spinbutton1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.spinbutton1]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox3.Add(this.hbox3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Maximum");
		this.hbox4.Add(this.label2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label2]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hscrollbar2 = new global::Gtk.HScrollbar(null);
		this.hscrollbar2.Name = "hscrollbar2";
		this.hscrollbar2.Adjustment.Upper = 100D;
		this.hscrollbar2.Adjustment.PageIncrement = 10D;
		this.hscrollbar2.Adjustment.PageSize = 10D;
		this.hscrollbar2.Adjustment.StepIncrement = 1D;
		this.hscrollbar2.Adjustment.Value = 90D;
		this.hbox4.Add(this.hscrollbar2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hscrollbar2]));
		w12.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinbutton2 = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.spinbutton2.CanFocus = true;
		this.spinbutton2.Name = "spinbutton2";
		this.spinbutton2.Value = 100D;
		this.hbox4.Add(this.spinbutton2);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.spinbutton2]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox3.Add(this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox4]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.GtkAlignment1.Add(this.vbox3);
		this.frame3.Add(this.GtkAlignment1);
		this.GtkLabel1 = new global::Gtk.Label();
		this.GtkLabel1.Name = "GtkLabel1";
		this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Depth Selection</b>");
		this.GtkLabel1.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel1;
		this.vbox2.Add(this.frame3);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame3]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Start");
		this.vbox4.Add(this.button1);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button1]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.vbox4.Add(this.button3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.button3]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		this.hbox6.Add(this.vbox4);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.vbox4]));
		w20.Position = 0;
		w20.Expand = false;
		w20.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox6.Add(this.fixed1);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.fixed1]));
		w21.Position = 1;
		this.vbox2.Add(this.hbox6);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
		w22.Position = 2;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.checkbutton1 = new global::Gtk.CheckButton();
		this.checkbutton1.CanFocus = true;
		this.checkbutton1.Name = "checkbutton1";
		this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString("Start 3D tracking");
		this.checkbutton1.DrawIndicator = true;
		this.checkbutton1.UseUnderline = true;
		this.vbox2.Add(this.checkbutton1);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.checkbutton1]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		this.vbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
		w24.Position = 2;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 710;
		this.DefaultHeight = 699;
		this.Show();
		this.hscrollbar1.ValueChanged += new global::System.EventHandler(this.ChangeMinDepth);
		this.spinbutton1.ValueChanged += new global::System.EventHandler(this.ChangeMinSpin);
		this.hscrollbar2.ValueChanged += new global::System.EventHandler(this.ChangeMaxDepth);
		this.spinbutton2.ValueChanged += new global::System.EventHandler(this.CHnageMaxSpin);
		this.button1.Clicked += new global::System.EventHandler(this.Start);
		this.button3.Clicked += new global::System.EventHandler(this.Stop);
	}
}
